# Generated by Django 4.1 on 2022-08-23 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuickSeqs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('fk_quick_id', models.IntegerField(blank=True, null=True)),
                ('createdat', models.DateTimeField(db_column='created_at')),
                ('updatedat', models.DateTimeField(db_column='updated_at')),
            ],
            options={
                'db_table': 'quick_seqs',
                'managed': False,
            },
        ),
    ]
